# model config for res50
model_hyp:
  # vision
  layers: [3, 4, 6, 3]
  output_dim: 1024
  heads: 8
  input_resolution: 224
  width: 64

  # text
  context_length: 77
  vocab_size: 49408
  transformer_width: 512
  transformer_heads: 8
  transformer_layers: 12